### PR TITLE
Function Default Arguments

### LINKED ISSUE #2109: Default arguments not working ?
The following works in CP, but not LP. 

```python
from random import random

from lpython import (i8, i32, i64, f32, f64,
                     u8, u32,
                     TypeVar, Const,
                     dataclass,
                     # random
                     )
from numpy import (empty, sqrt, float32, float64,
                   int8, int32, array, # ndarray
                   )


def coin_flip(probability : f64=f64(0.5)) -> i8:
    """roll 1 bit"""
    result : i8 = i8(0)
    r : f64 = random()
    if r < probability:
        result = i8(1)
    return result


def h() -> None:
    i : i32
    for i in range(10):
        coin : i8 = coin_flip()
        print(coin, end='')
    print('')


if __name__ == "__main__":
    h()
```

```bash
(lp) ┌─(~/CLionProjects/lpython/lasr/LP-pycharm)─────────────────────────────────────────────────────────────────────────────────────────────────────────(brian@Golf37:s000)─┐
└─(11:36:44 on brian-lasr ✹ ✭)──> PYTHONPATH='../../src/runtime/lpython' python issue2107.py                                                          1 ↵ ──(Wed,Jul05)─┘
1
1
1
1
1
0
1
1
0
0
(lp) ┌─(~/CLionProjects/lpython/lasr/LP-pycharm)─────────────────────────────────────────────────────────────────────────────────────────────────────────(brian@Golf37:s000)─┐
└─(11:36:49 on brian-lasr ✹ ✭)──> ~/CLionProjects/lpython/src/bin/lpython -I. issue2107.py                                                                ──(Wed,Jul05)─┘
semantic error: Number of arguments does not match in the function call
  --> issue2107.py:26:21
   |
26 |         coin : i8 = coin_flip()
   |                     ^^^^^^^^^^^ (found: '0', expected: '1')
```

### LINKED ISSUE #2509: Incorrect handling of default argument values
```python
def main(option: bool = False):
    print("option: ", option)

main()
```

```
(lp) ┌─(~/Documents/GitHub/masr/resources/reference)────────────────────────────────────────(brian@MacBook-Pro:s001)─┐
└─(08:43:14 on main ✹ ✭)──> PYTHONPATH=".:../src/runtime/lpython:.." LPYTHON_PY_MOD_NAME="" LPYTHON_PY_MOD_PATH="_lpython-tmp-test-cpython" python ../../../lpython/ISSUES/Issue2509.py
option:  False
(lp) ┌─(~/Documents/GitHub/masr/resources/reference)────────────────────────────────────────(brian@MacBook-Pro:s001)─┐
└─(08:43:40 on main ✹ ✭)──> lpython ../../../lpython/ISSUES/Issue2509.py                          ──(Thu,Feb08)─┘
semantic error: Number of arguments does not match in the function call
 --> ../../../lpython/ISSUES/Issue2509.py:5:1
  |
5 | main()
  | ^^^^^^ (found: '0', expected: '1')
```

### PR DESCRIPTION
**Pull request by assem2002**
fixes #2509 
fixes #2109  
completed the implementation of default arguments in functions.
# Code Flow
- `AST::functiondef` has `arguments` object as one of its members, this object has `m_defaults` and `n_defaults` which preserve the number of default arguments and `AST::expr_t` of the default constants.
- When we're building the variables of the function in `visit_functiondef( )` , we start pushing the ASR::expr_t of the defaults as a value for the variable when we reach the difference of `n_args` and `n_defaults` .
- When we start to call the function, we check if `n_pos_args` is less than `func.n_args` , if so, we start pushing the data from varibles in ASR::function_t  to ` Vec<ASR::call_arg_t>`,starting from the index n_pos_args.

# The code handles keyword arguments.

# serious issue to handle
The solution is build upon the idea of starting to make variable for the last number of  parameters. If the user writes a code like this 
```python
def whatever(first :str ="lpython",second :str):
    print(second)

whatever("foo") # result => lpython

``` 
as the lpython would be matched with the last parameter.

This should arise a syntax error like how Cpython does.

### CODE REVIEW

**Comment by assem2002** [comment]
checks result from setting default argument to the function parameters. I don't see how to handle such a thing.

**Comment by assem2002** [comment]
I think it's due to testing a function with default parameters in the wrong spot like the issue i mentioned above.
I will try to handle the AST to throw a syntax error when such a thing happens.

**Comment by assem2002** [comment]
The errors arises from converting the lpython code into "c code" as c doesn't provide default arguments.
Should i change the process of converting lpython-> c , so it doesn't make a default arguments assignment?

**Comment by assem2002** [comment]
If the solution seems to be doing the job correctly. I would start handling the syntax error to make the solution complete without any flaws.
I just want to make sure it's the right approach to handle such a problem.

File: src/lpython/semantics/python_ast_to_asr.cpp [hunk 1]
```diff
@@ -1141,6 +1141,19 @@ class CommonVisitor : public AST::BaseVisitor<Struct> {
                 args.reserve(al, n_pos_args + n_kwargs);
                 visit_expr_list(pos_args, n_pos_args, kwargs, n_kwargs,
                                 args, rt_subs, func, loc);
+            }
+        	if((n_pos_args+ n_kwargs) < func->n_args && (args.size() < func->n_args) ){
```
Comment (Shaikh-Ubaid) [inline src/lpython/semantics/python_ast_to_asr.cpp:1145]:
```suggestion
        if ((n_pos_args + n_kwargs) < func->n_args && (args.size() < func->n_args) ){
```

File: src/lpython/semantics/python_ast_to_asr.cpp [hunk 2]
```diff
@@ -1141,6 +1141,19 @@ class CommonVisitor : public AST::BaseVisitor<Struct> {
...
+                for(size_t def_arg = (n_pos_args+ n_kwargs) ; def_arg <(func->n_args) ;def_arg++){
```
Comment (Shaikh-Ubaid) [inline src/lpython/semantics/python_ast_to_asr.cpp:1146]:
```suggestion
                for (size_t def_arg = (n_pos_args+ n_kwargs); def_arg < func->n_args; def_arg++){
```

File: src/lpython/semantics/python_ast_to_asr.cpp [hunk 3]
```diff
@@ -1141,6 +1141,19 @@ class CommonVisitor : public AST::BaseVisitor<Struct> {
...
+                    ASR::symbol_t* sym = (ASR::down_cast<ASR::Var_t>((func->m_args)[def_arg]))->m_v;
```
Comment (Shaikh-Ubaid) [inline src/lpython/semantics/python_ast_to_asr.cpp:1147]:
```suggestion
                    ASR::symbol_t* sym = ASR::down_cast<ASR::Var_t>(func->m_args[def_arg])->m_v;
```

File: src/lpython/semantics/python_ast_to_asr.cpp [hunk 4]
```diff
@@ -1141,6 +1141,19 @@ class CommonVisitor : public AST::BaseVisitor<Struct> {
...
+                    ASR::Variable_t* var = ASR::down_cast<ASR::Variable_t>(sym);
+                    if(!(var->m_value)) {
```
Comment (Shaikh-Ubaid) [inline src/lpython/semantics/python_ast_to_asr.cpp:1149]:
```suggestion
                    if (var->m_value == nullptr) {
```

File: src/lpython/semantics/python_ast_to_asr.cpp [hunk 5]
```diff
@@ -4312,6 +4332,9 @@ class SymbolTableVisitor : public CommonVisitor<SymbolTableVisitor> {
             }
             ASR::accessType s_access = ASR::accessType::Public;
             ASR::presenceType s_presence = ASR::presenceType::Required;
+        	if (i >= default_arg_index_start){
```
Comment (Shaikh-Ubaid) [inline src/lpython/semantics/python_ast_to_asr.cpp:4335]:
```suggestion
        if (i >= default_arg_index_start){                
```

File: src/lpython/semantics/python_ast_to_asr.cpp (hunk 1 above)
Comment (Shaikh-Ubaid) [reply src/lpython/semantics/python_ast_to_asr.cpp:1145]: Also, I think `n_pos_args + n_kwargs` and `args.size()` will be same. So checking for `args.size() < func->n_args` seems redundant.

File: src/libasr/codegen/asr_to_c_cpp.h [hunk 6]
```diff
@@ -562,6 +562,7 @@ R"(#include <stdio.h>
                 if( is_c ) {
                     CDeclarationOptions c_decl_options;
                     c_decl_options.pre_initialise_derived_type = false;
+                    c_decl_options.do_not_initialize = true;
```
Comment (Shaikh-Ubaid) [inline src/libasr/codegen/asr_to_c_cpp.h:565]: Why do we need this change?

**Review by Shaikh-Ubaid — COMMENTED** [review]
Shared couple comments. Rest looks good. Let's add some integration tests and check if the implementation works as expected.

File: src/libasr/codegen/asr_to_c_cpp.h (hunk 6 above)
Comment (Shaikh-Ubaid) [reply src/libasr/codegen/asr_to_c_cpp.h:565]: I just read your commit message. I think its fine.

**Comment by Shaikh-Ubaid** [comment]
> If the solution seems to be doing the job correctly. I would start handling the syntax error to make the solution complete without any flaws. I just want to make sure it's the right approach to handle such a problem.

You can start another PR to support the semantic error. I suspect that the implementation might require updates in the parser.

**Comment by Shaikh-Ubaid** [comment]
Please mark it as "Ready for review" when ready.

File: src/lpython/semantics/python_ast_to_asr.cpp (hunk 1 above)
Comment (assem2002) [reply src/lpython/semantics/python_ast_to_asr.cpp:1145]: I wrote this part in the first time as you said, but built-in function  `complex()` made a huge problem.
The function seems to be making a call to some function without passing any positional arguments to the call ,although the call has `Vec<ASR::call_arg_t>`  parameter filled with arguments to be placed in the called function.
# Brief 
- Sometimes the call is depending on `n_pos_args + n_kwargs` as you mentioned and that should be enough, but sometimes it depends on `args.size()` .
- `n_pos_args + n_kwargs` evaluate to => 0 .... while 'args.size()' evaluate to => (**larger than 0**).

File: src/lpython/semantics/python_ast_to_asr.cpp (hunk 5 above)
Comment (assem2002) [reply src/lpython/semantics/python_ast_to_asr.cpp:4335]: I'll push the new reviewed code now, and I'll work on integration test to push soon.

**Comment by assem2002** [comment]
> > If the solution seems to be doing the job correctly. I would start handling the syntax error to make the solution complete without any flaws. I just want to make sure it's the right approach to handle such a problem.
> 
> You can start another PR to support the semantic error. I suspect that the implementation might require updates in the parser.

I think we can handle such a thing on the parser level as you mentioned.
we can handle it by using a `default_argumets_started_ flag = false` to throw an error if ==> `default_argumets_started_ flag = true` and the current argument being built doesn't have a default argument.

**Comment by Shaikh-Ubaid** [comment]
>we can handle it by using a default_argumets_started_ flag = false to throw an error if ==> default_argumets_started_ flag = true and the current argument being built doesn't have a default argument.

Go ahead and submit a PR with your approach and I will take a look.

**Comment by Shaikh-Ubaid** [comment]
I suggest implementing the semantic error in a separate PR.

File: src/lpython/semantics/python_ast_to_asr.cpp (hunk 1 above)
Comment (Shaikh-Ubaid) [reply src/lpython/semantics/python_ast_to_asr.cpp:1145]: I see. I think in that case, we can directly use `if (args.size() < func->n_args)`. Can you try it and share if it works?

You also need to update the initialization in the below loop `for(size_t def_arg = args.size(); def_arg < func->n_args; def_arg++)`

Comment (assem2002) [reply src/lpython/semantics/python_ast_to_asr.cpp:1145]: Yeah, you're right. Using `arg.size()` only would do the job.

**Comment by assem2002** [comment]
> I suggest implementing the semantic error in a separate PR.

I'll do after handling this PR

> I suggest implementing the semantic error in a separate PR.

I'll right after completing this PR

**Comment by assem2002** [comment]
@Shaikh-Ubaid 

I faced a test case which I can't say whether it's a valid test case or not
the following:
```python

def default_func(x : str ="Hello" ,y : str = " ", z : str = "World") ->str:
    return x + y + z

default_func(z="lpython")
```

It results in the following error:
```shell
semantic error: default_func() got multiple values for argument 'z'
  --> ../../integration_tests/def_func_01.py:49:20
   |
49 |     test_06 :str = default_func(z="lpython")
   |                    ^^^^^^^^^^^^^^^^^^^^^^^^^ 

```

should I handle this in the parsing phase to prevent user form passing keyword arguments for the last parameters, instead the used can pass keyword arguments only if it fill some sequence in the beginning of the parameter list like that:
```python
default_func(y = "///",x="Hi")
```

**Comment by Shaikh-Ubaid** [comment]
>I faced a test case which I can't say whether it's a valid test case or not

If the test case runs in cpython then its a valid test case.

**Comment by assem2002** [comment]
> > I faced a test case which I can't say whether it's a valid test case or not
> 
> If the test case runs in cpython then its a valid test case.

Actually it passes this testcase. I will try to find a way to handle it.

**Comment by assem2002** [comment]
@Shaikh-Ubaid 
I handled the tests case
```python
def default_func(x : str ="Hello" ,y : str = " ", z : str = "World") ->str:
    return x + y + z

    test_09 :str = default_func(y = "++",z = "LPython")
    print("test_09 is =>",test_09)
    assert test_09 == "Hello++LPython"

    test_10 :str = default_func("Welcome",z = "LPython")
    print("test_10 is =>",test_10)
    assert test_10 == "Welcome LPython"
```

# Solution Flow
- If only positional arguments are passed and aren't matching `func->n_args`,  we start from the last argument in function_t and push back in `Vec<args>`, if there's no value to push then break.
- If there's keyword arguments passed, We reserve `Vec<args>` with `func->n_args` and then `visit_expr_list()` starts to place set all arguments to `nullptr`, then pushes back positional arguments, then sets keyword arguments in its desired index in `Vec<args>` , then we loop on` Vec<args> ` to see if there's a `nullptr` arg that we can have a matching default argument for.

**Comment by certik** [comment]
Thanks!

To implement default arguments, the following must be done:

* At the function definition time, find the default argument and put it into the argument's Variable `symbolic_value` into the symbol table
* At the function call site, simply lookup any default arguments in ASR, and if present, use them by explicitly inserting them

The alternative design is to not even insert them and sort it out inside the function, but I would not do this, since it is not explicit. I would always insert them at the call site.

**Comment by kmr-srbh** [comment]
@assem2002 could you please test for this case?
```python
from lpython import i32

def fn(defarg1: str="default", arg: i32, defarg2: str="default") -> i32:
    return 1


fn()
```

This should throw an error.

**Comment by assem2002** [comment]
> @assem2002 could you please test for this case?
> 
> ```python
> from lpython import i32
> 
> def fn(defarg1: str="default", arg: i32, defarg2: str="default") -> i32:
>     return 1
> 
> 
> fn()
> ```
> 
> This should throw an error.

Yeah it should, but unfortunately it doesn't 
I talked with **Shaikh Ubaid**  about this, We agreed to push another pull request to handle this problem on the parsing stage not in the ASR stage.

**Comment by assem2002** [comment]
> * symbol table

Does that mean the AST of a call to a function with default arguments will include the default arguments passed even if they weren't provided by user? If so, isn't the whole AST is built then ASR?

Or what you mean is to edit the call to 'make_call_helper()'  to include the default arguments?

**Comment by assem2002** [comment]
> Thanks!
> 
> To implement default arguments, the following must be done:
> 
>     * At the function definition time, find the default argument and put it into the argument's Variable `symbolic_value` into the symbol table
> 
>     * At the function call site, simply lookup any default arguments in ASR, and if present, use them by explicitly inserting them
> 
> 
> The alternative design is to not even insert them and sort it out inside the function, but I would not do this, since it is not explicit. I would always insert them at the call site.



Does that mean the AST of a call to a function with default arguments will include the default arguments passed even if they weren't provided by user? If so, isn't the whole AST is built then ASR?

Or what you mean is to edit the call to 'make_call_helper()' to include the default arguments?

**Comment by Shaikh-Ubaid** [comment]
The approach that Ondrej shared comprises of the following two steps:

### Step 1

For default function arguments, their default value should be inserted in the functions symbol table inside the Variable declaration. Precisely, the default value should be inserted in the variable's `symbolic_value` and `value` in its declaration inside the symbol table of each function.

### Step 2

For each function call, whenever we need to use the default argument value we can simply lookup the symbol table of the called function, access the `symbolic_value` (or `value`) for the variable whose default value we need and insert this default value in the function call.

Please let me know if this makes it clear.

**Comment by assem2002** [comment]
> The approach that Ondrej shared comprises of the following two steps:
> ### Step 1
> 
> For default function arguments, their default value should be inserted in the functions symbol table inside the Variable declaration. Precisely, the default value should be inserted in the variable's `symbolic_value` and `value` in its declaration inside the symbol table of each function.
> ### Step 2
> 
> For each function call, whenever we need to use the default argument value we can simply lookup the symbol table of the called function, access the `symbolic_value` (or `value`) for the variable whose default value we need and insert this default value in the function call.
> 
> Please let me know if this makes it clear.

I got the first step.
does the second step should be similar to that? :
```c++
            (for size_t i = index_start_def_arguments; i < func-> n_args; i++){
                ASR::var_t* var  = ASR::down_cast<ASR::Var_t>(func->m_args[i]);
                std::string symbol_name = ASRUtils::symbol_name(arg_Var->m_v);
                ASR::symbol_t* sym = func->m_symtab->getsymbol(symbol_name);
                //then accessing the value, and pushing in call_args vector.
            }
```

**Comment by Shaikh-Ubaid** [comment]
>does the second step should be similar to that?

Seems in the right direction. Also, note that you can simply get the `symbol` from `Var_t` as follows:
```console
ASR::Var_t* var  = ASR::down_cast<ASR::Var_t>(func->m_args[i]);
ASR::symbol_t* sym = var->m_v;
```

**Comment by assem2002** [comment]
> Seems in the right direction. Also, note that you can simply get the `symbol` from `Var_t` as follows:

actually I'm confused at the moment. My PR handles the issue of passing the default arguments by sorting the arguments in `Vec<call_args>`,
```C++
  for (size_t def_arg = args.size(); def_arg < func->n_args; def_arg++){
      ASR::symbol_t* sym = ASR::down_cast<ASR::Var_t>(func->m_args[def_arg])->m_v;
      ASR::Variable_t* var = ASR::down_cast<ASR::Variable_t>(sym);
      if (var->m_value == nullptr) {
          break;
      }
      ASR::call_arg_t call_arg;
      args.push_back(al,call_arg);
      args.p[def_arg].loc = ((var->m_value)->base).loc;
      args.p[def_arg].m_value = (var->m_value);
```

 which Ondrej thinks isn't explicit, so he is proposing to pushing arguments by looking up them in the symbol Table and get the value in symbolic value if exist.This approach could be done like that:

```C++
(for size_t i = index_start_def_arguments; i < func-> n_args; i++){
    ASR::var_t* var  = ASR::down_cast<ASR::Var_t>(func->m_args[i]);
    std::string symbol_name = ASRUtils::symbol_name(arg_Var->m_v);
    ASR::symbol_t* sym = func->m_symtab->getsymbol(symbol_name);
    //then accessing the value, and pushing in call_args vector.
}
```
which seems better i can just look up the arguments by their name instead of manipulating the logic of the arguments positions passed the `make_call_helper( )`. Using previous approach is really more explicit to the reader of the code and it would handle the issue of [keyword arguments](https://github.com/lcompilers/lpython/pull/2618#issuecomment-2022117366) that appeared in some test cases in more explicit way.

I hope I got what you mean. If I completely lost track of what you want to implement, I hope you can guide me through an article or something.

**Comment by Shaikh-Ubaid** [comment]
>which Ondrej thinks isn't explicit, so he is proposing the approach of pushing arguments by looking up their values in the symbol Table and get the value in symbolic value if exist

As of now, I think the symbolic value for a functions default argument is not inserted. That is, the symbolic value for the default argument is currently `null` at the ASR level. Even if the user has provided the default value in the AST, we just skip processing it while constructing the ASR.

As a part of this PR, the first step should be to process the default values of function arguments (if any) provided in the AST and ensure that these get appropriately reflected in the `symbolic_value` of the function argument declaration in the function's symbol table.

Please let me know if this helps.

**Comment by assem2002** [comment]
> processing it while constructing the ASR.

I read about interpreter design in the classic SICP, and I see what you meant to say. Though the PR's current solution is working fine, but still not the convenient  way to do such a thing.
I think the PR is close to the desired solution,I'll push some edits to meet these requirements.

**Comment by assem2002** [comment]
@Shaikh-Ubaid @certik 
Now I fetch the value of the default arguments by looking up the symbol table of the scope of the function that has been called.
Let me know if that's the right approach to do so or it needs to get changed.

File: src/lpython/semantics/python_ast_to_asr.cpp [hunk 7]
```diff
@@ -704,6 +704,21 @@ class CommonVisitor : public AST::BaseVisitor<Struct> {
...
             call_args_vec.p[arg_pos].m_value = expr;
         }
+        //Filling missing arguments with its default argument passed in function definition (if existed).
+        for(size_t i = 0; i < orig_func->n_args; i++ ){
+            if(call_args_vec.p[i].m_value == nullptr){
+                ASR::symbol_t* sym = ASR::down_cast<ASR::Var_t>(orig_func->m_args[i])->m_v;
+                std::string variable_name = ASR::down_cast<ASR::Variable_t>(sym)->m_name;
+                ASR::Variable_t* var = ASR::down_cast<ASR::Variable_t>(orig_func->m_symtab->get_symbol(variable_name));
+                if (var->m_symbolic_value == nullptr){
+                    call_args_vec.reserve(al, n_pos_args + n_kwargs); //deprecate Vec container, so it raise error later.
```
Comment (certik) [inline src/lpython/semantics/python_ast_to_asr.cpp:714]: Something is not right here --- why do you need to call `reserve` here?

File: src/lpython/semantics/python_ast_to_asr.cpp [hunk 8]
```diff
@@ -1139,9 +1154,23 @@ class CommonVisitor : public AST::BaseVisitor<Struct> {
         if (ASR::is_a<ASR::Function_t>(*s)) {
             ASR::Function_t *func = ASR::down_cast<ASR::Function_t>(s);
             if( n_kwargs > 0 && !is_generic_procedure ) {
-                args.reserve(al, n_pos_args + n_kwargs);
+                args.reserve(al, func->n_args);
                 visit_expr_list(pos_args, n_pos_args, kwargs, n_kwargs,
                                 args, rt_subs, func, loc);
+            }
+        	else if(args.size() < func->n_args){
```
Comment (certik) [inline src/lpython/semantics/python_ast_to_asr.cpp:1161]:
```suggestion
            } else if (args.size() < func->n_args) {
```

File: integration_tests/def_func_01.py [hunk 9]
```diff
@@ -0,0 +1,76 @@
...
+
+def test_all():
+
+    test_01 : i32  = factorial_1(5,0)
+    print("test_01 is =>",test_01)
+    assert test_01 == 120
+
+    test_02 : i32  = factorial_1(1,5555)
+    print("test_02 is =>",test_02)
+    assert test_02 == 5555
```
Comment (certik) [inline integration_tests/def_func_01.py:35]: Add a test for not passing in the second argument and ensure it returns the default value "1".

File: integration_tests/def_func_01.py [hunk 10]
```diff
@@ -0,0 +1,76 @@
...
+def factorial_2(x: i32, y:i32=3 ,z:i32 =2) ->i32:
+    if x ==4:
+        return x * y * z
+    return x * factorial_2(x-1)
+
+def default_func(x : str ="Hello" ,y : str = " ", z : str = "World") ->str:
+    return x + y + z
+
+
+def even_positons(iterator : i32 , to_add : str = "?")-> str:
```
Comment (certik) [inline integration_tests/def_func_01.py:17]: Did you mean:
```suggestion
def even_positions(iterator : i32 , to_add : str = "?")-> str:
```

File: src/lpython/semantics/python_ast_to_asr.cpp [hunk 11]
```diff
@@ -704,6 +704,21 @@ class CommonVisitor : public AST::BaseVisitor<Struct> {
             call_args_vec.p[arg_pos].loc = expr->base.loc;
             call_args_vec.p[arg_pos].m_value = expr;
         }
+        //Filling missing arguments with its default argument passed in function definition (if existed).
```
Comment (certik) [inline src/lpython/semantics/python_ast_to_asr.cpp:707]:
```suggestion
        // Filling missing arguments with their defaults passed in function definition (if present).
```

**Review by certik — COMMENTED** [review]
I think this is the right approach. Where is the `m_symbolic_value` being set in the first place? I couldn't see it in the PR. I left some minor comments.

Can you please also test this by having the function with default arguments in a separate module?

@Shaikh-Ubaid can you please also review it?

File: src/lpython/semantics/python_ast_to_asr.cpp [hunk 12]
```diff
@@ -659,7 +659,7 @@ class CommonVisitor : public AST::BaseVisitor<Struct> {
 
         // Fill the whole call_args_vec with nullptr
         // This is for error handling later on.
-        for( size_t i = 0; i < n_pos_args + n_kwargs; i++ ) {
+         for( size_t i = 0; i < call_args_vec.max; i++ ) {
```
Comment (Shaikh-Ubaid) [inline src/lpython/semantics/python_ast_to_asr.cpp:662]: @assem2002 please, could you explain why we need this change?

File: integration_tests/def_func_01.py [hunk 13]
```diff
@@ -0,0 +1,80 @@
...
+    test_10 :str = default_func("Welcome",z = "LPython")
+    print("test_10 is =>",test_10)
+    assert test_10 == "Welcome LPython"
+test_all()
+
+
+
+
+
+
```
Comment (Shaikh-Ubaid) [inline integration_tests/def_func_01.py:79]: Please remove these stray blank lines at the end of the file.

File: integration_tests/def_func_01.py [hunk 14]
```diff
@@ -0,0 +1,80 @@
...
+    assert test_08 == "WX?X?X?X?X"
+
+    test_09 :str = default_func(y = "++",z = "LPython")
+    print("test_09 is =>",test_09)
+    assert test_09 == "Hello++LPython"
+
+    test_10 :str = default_func("Welcome",z = "LPython")
+    print("test_10 is =>",test_10)
+    assert test_10 == "Welcome LPython"
+test_all()
```
Comment (Shaikh-Ubaid) [inline integration_tests/def_func_01.py:73]: In this test, @assem2002 do you mind using appropriate and consistent spacing for example `my_func(x: i32 = 10, y: str = "abc")` and `print("test_09 is =>", test_09)` .

File: integration_tests/def_func_01.py [hunk 15]
```diff
@@ -0,0 +1,80 @@
...
+def even_positions(iterator : i32 , to_add : str = "?")-> str:
+    if (iterator == 10): return ""
+
+    if iterator%2 == 0 :
+        return to_add + even_positions(iterator+1,"X")
+
+    return to_add +even_positions(iterator+1)
+
+
+
```
Comment (Shaikh-Ubaid) [inline integration_tests/def_func_01.py:26]:
```suggestion
```

**Review by Shaikh-Ubaid — COMMENTED** [review]
With respect to the previous implementation, I couldn't find any/much difference. Please, could you highlight what new changes were added?

**Comment by Shaikh-Ubaid** [comment]
>Where is the m_symbolic_value being set in the first place? I couldn't see it in the PR. I left some minor comments.

I think it is not being set. @assem2002 as we shared before, the `m_symbolic_value` should be first set (it should be visible for the default parameters of the function when we do `--show-asr`). Then, on function call when sufficient arguments are not provided, we simply look up the `m_symbolic_value` for the missing arguments and insert it in the function call.

**Comment by assem2002** [comment]
> > Where is the m_symbolic_value being set in the first place? I couldn't see it in the PR. I left some minor comments.
> 
> I think it is not being set. @assem2002 as we shared before, the `m_symbolic_value` should be first set (it should be visible for the default parameters of the function when we do `--show-asr`). Then, on function call when sufficient arguments are not provided, we simply look up the `m_symbolic_value` for the missing arguments and insert it in the function call.

It does appear in the ASR

the symbolic_value of the variable of the function parameters is set in the following line of code 
```cpp
  if (i >= default_arg_index_start){
      size_t default_arg_index = i - default_arg_index_start;
      this->visit_expr(*(x.m_args.m_defaults[default_arg_index]));
      init_expr = ASRUtils::EXPR(tmp);  // <<<<<<<<<<<<<<<<<<<<<<<<<HERE
```
`init_expr` is the value that is going to be passed to `symbolic_value` while building the variable in `make_variable( )`

**Comment by assem2002** [comment]
> > > Where is the m_symbolic_value being set in the first place? I couldn't see it in the PR. I left some minor comments.
> > 
> > 
> > I think it is not being set. @assem2002 as we shared before, the `m_symbolic_value` should be first set (it should be visible for the default parameters of the function when we do `--show-asr`). Then, on function call when sufficient arguments are not provided, we simply look up the `m_symbolic_value` for the missing arguments and insert it in the function call.
> 
> It does appear in the ASR
> 
> ```python
> def default_func(x : str ="Hello", y : str = " ", z : str = "World") ->str:
>     return x + y + z
> ```
> 
> Screenshot from 2024-04-30 02-10-35
> 
> the symbolic_value of the variable of the function parameters is set in the following line of code
> 
> ```c++
>   if (i >= default_arg_index_start){
>       size_t default_arg_index = i - default_arg_index_start;
>       this->visit_expr(*(x.m_args.m_defaults[default_arg_index]));
>       init_expr = ASRUtils::EXPR(tmp);  // <<<<<<<<<<<<<<<<<<<<<<<<<HERE
> ```
> 
> `init_expr` is the value that is going to be passed to `symbolic_value` while building the variable in `make_variable( )`
> 
> and yeah i know this PR isn't much different, but while processing a function call, instead of fetching the values directly we search the scope for the name of the arguments. I think it's a matter of clarity in the code not more than that.

@Shaikh-Ubaid

**Comment by certik** [comment]
Indeed, it seems it is already set in ASR.

**Comment by assem2002** [comment]
> Indeed, it seems it is already set in ASR.

In the current version on lpython repo, The ASR of any function doesn't know any information about the default arguments as it never get passed to the `function_t` object while building the ASR

File: src/lpython/semantics/python_ast_to_asr.cpp [hunk 16]
```diff
@@ -1139,9 +1154,22 @@ class CommonVisitor : public AST::BaseVisitor<Struct> {
...
                 visit_expr_list(pos_args, n_pos_args, kwargs, n_kwargs,
                                 args, rt_subs, func, loc);
+            } else if (args.size() < func->n_args) {
+                for (size_t def_arg = args.size(); def_arg < func->n_args; def_arg++){
+                    ASR::symbol_t* sym = ASR::down_cast<ASR::Var_t>(func->m_args[def_arg])->m_v;
+                    std::string variable_name = ASR::down_cast<ASR::Variable_t>(sym)->m_name;
+                    ASR::Variable_t* var = ASR::down_cast<ASR::Variable_t>(func->m_symtab->get_symbol(variable_name));
+                    if(var->m_symbolic_value == nullptr) {
+                        break;
+                    }
```
Comment (Shaikh-Ubaid) [inline src/lpython/semantics/python_ast_to_asr.cpp:1167]: Why do we `break` here? Is this a case where `m_symbolic_value` is expected/needed but is not available? If so, then I think we should throw a `SemanticError()` instead of the `break`.

File: src/lpython/semantics/python_ast_to_asr.cpp (hunk 12 above)
Comment (Shaikh-Ubaid) [reply src/lpython/semantics/python_ast_to_asr.cpp:662]: I think I get it. I think we can better use `orig_func->n_args` here.

File: src/lpython/semantics/python_ast_to_asr.cpp [hunk 17]
```diff
@@ -704,6 +704,21 @@ class CommonVisitor : public AST::BaseVisitor<Struct> {
             call_args_vec.p[arg_pos].loc = expr->base.loc;
             call_args_vec.p[arg_pos].m_value = expr;
         }
+        //Filling missing arguments with its default argument passed in function definition (if existed).
+        for(size_t i = 0; i < orig_func->n_args; i++ ){
+            if(call_args_vec.p[i].m_value == nullptr){
+                ASR::symbol_t* sym = ASR::down_cast<ASR::Var_t>(orig_func->m_args[i])->m_v;
+                std::string variable_name = ASR::down_cast<ASR::Variable_t>(sym)->m_name;
+                ASR::Variable_t* var = ASR::down_cast<ASR::Variable_t>(orig_func->m_symtab->get_symbol(variable_name));
```
Comment (Shaikh-Ubaid) [inline src/lpython/semantics/python_ast_to_asr.cpp:712]:
```suggestion
                ASR::Variable_t* var = ASRUtils::EXPR2VAR(orig_func->m_args[i]);
```

File: src/lpython/semantics/python_ast_to_asr.cpp (hunk 7 above)
Comment (Shaikh-Ubaid) [reply src/lpython/semantics/python_ast_to_asr.cpp:714]: Right. I think we should better throw a `SemanticError` when a default value is expected/needed, but is `nullptr`.

File: src/lpython/semantics/python_ast_to_asr.cpp [hunk 18]
```diff
@@ -1139,9 +1154,22 @@ class CommonVisitor : public AST::BaseVisitor<Struct> {
...
             if( n_kwargs > 0 && !is_generic_procedure ) {
-                args.reserve(al, n_pos_args + n_kwargs);
+                args.reserve(al, func->n_args);
                 visit_expr_list(pos_args, n_pos_args, kwargs, n_kwargs,
                                 args, rt_subs, func, loc);
+            } else if (args.size() < func->n_args) {
+                for (size_t def_arg = args.size(); def_arg < func->n_args; def_arg++){
+                    ASR::symbol_t* sym = ASR::down_cast<ASR::Var_t>(func->m_args[def_arg])->m_v;
+                    std::string variable_name = ASR::down_cast<ASR::Variable_t>(sym)->m_name;
+                    ASR::Variable_t* var = ASR::down_cast<ASR::Variable_t>(func->m_symtab->get_symbol(variable_name));
```
Comment (Shaikh-Ubaid) [inline src/lpython/semantics/python_ast_to_asr.cpp:1164]:
```suggestion
                    ASR::Variable_t* var = ASRUtils::EXPR2VAR(func->m_args[def_arg]);
```

File: src/lpython/semantics/python_ast_to_asr.cpp [hunk 19]
```diff
@@ -1139,9 +1154,22 @@ class CommonVisitor : public AST::BaseVisitor<Struct> {
         if (ASR::is_a<ASR::Function_t>(*s)) {
             ASR::Function_t *func = ASR::down_cast<ASR::Function_t>(s);
             if( n_kwargs > 0 && !is_generic_procedure ) {
-                args.reserve(al, n_pos_args + n_kwargs);
+                args.reserve(al, func->n_args);
                 visit_expr_list(pos_args, n_pos_args, kwargs, n_kwargs,
                                 args, rt_subs, func, loc);
+            } else if (args.size() < func->n_args) {
```
Comment (Shaikh-Ubaid) [inline src/lpython/semantics/python_ast_to_asr.cpp:1160]: After going through the rest of the changes, it seems that this `else if` block might not be required. @assem2002 Can you try removing this `else-if` block and see if things still work?

**Review by Shaikh-Ubaid — COMMENTED** [review]
Shared couple comments. Seems like in a good direction.

File: src/lpython/semantics/python_ast_to_asr.cpp (hunk 19 above)
Comment (Shaikh-Ubaid) [reply src/lpython/semantics/python_ast_to_asr.cpp:1160]: Second thought: It might be needed. It looks like a better place for this can be inside the function `void visit_expr_list(AST::expr_t** exprs, size_t n, Vec<ASR::call_arg_t>& call_args_vec)`, but we can do that later. For now the current place is fine for me.

**Comment by Shaikh-Ubaid** [comment]
Please mark as "Ready for review" when ready.

**Comment by assem2002** [comment]
> Please mark as "Ready for review" when ready.

@Shaikh-Ubaid 
I need your opinion on this [link](https://github.com/lcompilers/lpython/pull/2618#discussion_r1585139929) and this [link](https://github.com/lcompilers/lpython/pull/2618#discussion_r1585109447) .
to handle your suggestions on the code properly.

**Comment by Shaikh-Ubaid** [comment]
https://github.com/lcompilers/lpython/pull/2618#discussion_r1585139929 is a simple code improvement suggestion. Please try it and share if it works.

For https://github.com/lcompilers/lpython/pull/2618#discussion_r1585109447, I am unsure why we have used `break`.

**Comment by assem2002** [comment]
> [#2618 (comment)](https://github.com/lcompilers/lpython/pull/2618#discussion_r1585139929) is a simple code improvement suggestion. Please try it and share if it works.
> 
> For [#2618 (comment)](https://github.com/lcompilers/lpython/pull/2618#discussion_r1585109447), I am unsure why we have used `break`.

For the break thing : I loop through the not-passed function parameters and try to look for their defaults (if exist), once i notice i have a missed parameter with no default for it, i break the loop as there's no need to proceed with the loop (**NOTICE** : default values are passed sequentially at the end of the parameters list).
............
About the [modifications](https://github.com/lcompilers/lpython/pull/2618#discussion_r1585139929) I'll test it and let you know about it.

**Comment by Shaikh-Ubaid** [comment]
Please mark as "Ready for review" when ready.

**Comment by assem2002** [comment]
@Shaikh-Ubaid 
Okay, I'll write such an error message and let you know.
but why there wasn't such a message before?

**Comment by Shaikh-Ubaid** [comment]
>but why there wasn't such a message before?

Previously we just checked for mismatch in the number of arguments. With the changes in this PR, I think we can now pinpoint to which particular argument is missing.

File: src/lpython/semantics/python_ast_to_asr.cpp [hunk 20]
```diff
@@ -704,6 +704,32 @@ class CommonVisitor : public AST::BaseVisitor<Struct> {
...
+        std::string missed_args_names;
+        size_t missed_args_count =0;
+        for(size_t i = 0; i < orig_func->n_args; i++ ){
+            if(call_args_vec.p[i].m_value == nullptr){
+                ASR::Variable_t* var = ASRUtils::EXPR2VAR(orig_func->m_args[i]);
+                if (var->m_symbolic_value == nullptr){
+                    missed_args_names+="'" + (std::string) var->m_name + "' and ";
+                    missed_args_count++;
+                }
+                else{
```
Comment (Shaikh-Ubaid) [inline src/lpython/semantics/python_ast_to_asr.cpp:717]:
```suggestion
                    missed_args_names+="'" + std::string(var->m_name) + "' and ";
                    missed_args_count++;
                } else{
```

File: src/lpython/semantics/python_ast_to_asr.cpp [hunk 21]
```diff
@@ -1139,9 +1165,37 @@ class CommonVisitor : public AST::BaseVisitor<Struct> {
...
+                size_t missed_args_count =0;
+                for (size_t def_arg = args.size(); def_arg < func->n_args; def_arg++){
+                    ASR::Variable_t* var = ASRUtils::EXPR2VAR(func->m_args[def_arg]);
+                    if(var->m_symbolic_value == nullptr) {
+                        missed_args_names+= "'" + (std::string)var->m_name + "' and ";
+                        missed_args_count++;
+                    }
+                    else{
+
+                        ASR::call_arg_t call_arg;
```
Comment (Shaikh-Ubaid) [inline src/lpython/semantics/python_ast_to_asr.cpp:1182]:
```suggestion
                        missed_args_names+= "'" + std::string(var->m_name) + "' and ";
                        missed_args_count++;
                    } else{
                        ASR::call_arg_t call_arg;
```

File: src/lpython/semantics/python_ast_to_asr.cpp [hunk 22]
```diff
@@ -1139,9 +1165,37 @@ class CommonVisitor : public AST::BaseVisitor<Struct> {
...
+                        call_arg.m_value = var->m_symbolic_value;
+                        call_arg.loc = (var->m_symbolic_value->base).loc;
+                        args.push_back(al,call_arg);       
+                    }
+                }
+                if(missed_args_count > 0){
+                    missed_args_names = missed_args_names.substr(0,missed_args_names.length() - 5);
+                    diag.add(diag::Diagnostic(
+                    "Number of arguments does not match in the function call",
```
Comment (Shaikh-Ubaid) [inline src/lpython/semantics/python_ast_to_asr.cpp:1191]: @assem2002 Do you mind adding an error reference test for this?

**Review by Shaikh-Ubaid — COMMENTED** [review]
Shared some minor changes. Rest looks good. I think the PR will be good to merge after these changes are handled.

File: src/lpython/semantics/python_ast_to_asr.cpp (hunk 20 above)
Comment (Shaikh-Ubaid) [reply src/lpython/semantics/python_ast_to_asr.cpp:717]: @assem2002 it would be great if you could update the above to follow the existing style/formatting.

**Review by Shaikh-Ubaid — COMMENTED** [review]
Shared a comment. The added test cases look great! Thanks for this!

**Comment by kmr-srbh** [comment]
I think there might be some more changes required with the PR. The following must have failed, but executes normally:
```python
from lpython import i32

def fn(arg1: i32, arg2: i32, arg3: i32=1) -> i32:
    return arg1 + arg2 + arg3

print(fn(arg3=2, 1, 3))
```
```console
(lp) saurabh-kumar@Awadh:~/Projects/System/lpython$ ./src/bin/lpython ./examples/example.py
6
```

CPython throws the expected `SyntaxError` due to positional arguments following keyword arguments. I found the following error when thinking of some more testcases to add.

File: src/lpython/semantics/python_ast_to_asr.cpp [hunk 23]
```diff
@@ -4290,6 +4343,11 @@ class SymbolTableVisitor : public CommonVisitor<SymbolTableVisitor> {
             std::string arg_s = arg;
             ASR::expr_t *value = nullptr;
             ASR::expr_t *init_expr = nullptr;
+            if (i >= default_arg_index_start){
+                size_t default_arg_index = i - default_arg_index_start;
+                this->visit_expr(*(x.m_args.m_defaults[default_arg_index]));
```
Comment (kmr-srbh) [inline src/lpython/semantics/python_ast_to_asr.cpp:4348]:
```suggestion
            AST::expr_t *def_arg = nullptr;
            size_t default_arg_index;
            if (i >= default_arg_index_start){
                default_arg_index = i - default_arg_index_start;
                def_arg = x.m_args.m_defaults[default_arg_index];
                this->visit_expr(*def_arg);
```

We can be a little readable here.

File: src/lpython/semantics/python_ast_to_asr.cpp [hunk 24]
```diff
@@ -1139,9 +1165,35 @@ class CommonVisitor : public AST::BaseVisitor<Struct> {
...
+                        ASR::call_arg_t call_arg;
+                        call_arg.m_value = var->m_symbolic_value;
+                        call_arg.loc = (var->m_symbolic_value->base).loc;
+                        args.push_back(al,call_arg);       
+                    }
+                }
+                if(missed_args_count > 0){
+                    missed_args_names = missed_args_names.substr(0,missed_args_names.length() - 5);
+                    diag.add(diag::Diagnostic(
+                    "Number of arguments does not match in the function call",
```
Comment (kmr-srbh) [inline src/lpython/semantics/python_ast_to_asr.cpp:1189]:
```suggestion
                    "Number of arguments in the function call do not match the function definition",
```

File: src/lpython/semantics/python_ast_to_asr.cpp [hunk 25]
```diff
@@ -704,6 +704,32 @@ class CommonVisitor : public AST::BaseVisitor<Struct> {
...
+                }
+                else{
+                    call_args_vec.p[i].m_value = var->m_symbolic_value;
+                }
+            }
+        }
+        if(missed_args_count > 0){
+            missed_args_names = missed_args_names.substr(0,missed_args_names.length() - 5);
+            diag.add(diag::Diagnostic(
+                "Number of arguments does not match in the function call",
```
Comment (kmr-srbh) [inline src/lpython/semantics/python_ast_to_asr.cpp:725]:
```suggestion
                "Number of arguments in the function call do not match the function definition",
```

**Review by kmr-srbh — CHANGES_REQUESTED** [review]
I have suggested some style changes below. Please have a look.

**Comment by assem2002** [comment]
> I think there might be some more changes required with the PR. The following must have failed, but executes normally:
> 
> ```python
> from lpython import i32
> 
> def fn(arg1: i32, arg2: i32, arg3: i32=1) -> i32:
>     return arg1 + arg2 + arg3
> 
> print(fn(arg3=2, 1, 3))
> ```
> 
> ```
> (lp) saurabh-kumar@Awadh:~/Projects/System/lpython$ ./src/bin/lpython ./examples/example.py
> 6
> ```
> 
> CPython throws the expected `SyntaxError` due to positional arguments following keyword arguments. I found the following error when thinking of some more testcases to add.
> 
> I think this PR is specifically handling the filling of default arguments. We can focus on this issue later if this PR is not the right place to handle it.

Yeah you're right. We suggest to handle this syntax error in another issue in addition to that problem too [link](https://github.com/lcompilers/lpython/pull/2618#issuecomment-2034517728)

**Comment by Shaikh-Ubaid** [comment]
The PR seems to be getting longer. So let's merge this and work iteratively on the rest of the things (if any) in a new PR.

**Review by Shaikh-Ubaid — APPROVED** [review]
It looks great! Thanks for this! Amazing work! I appreciate it.
