### PR TITLE
Fix zero slice step

### LINKED ISSUE #1833: Edge case in slice step of Lists
Slice step 0 not checked.

```
def g():
    lst:list[i32] = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
    print(lst[0:10:0])
g()

(lp) faze-geek@DESKTOP-497JDCU:~/lpython/lpython$ python try.py
    print(lst[0:10:0])
          ~~~^^^^^^^^
ValueError: slice step cannot be zero
(lp) faze-geek@DESKTOP-497JDCU:~/lpython/lpython$ ./src/bin/lpython try.py
[]
```

### PR DESCRIPTION
**Pull request by kabra1110**
Fixes #1833.
I have added the check for any slice step. This holds for strings and lists.
Are there places where zero step is allowed? (I don't think so.)

### CODE REVIEW

File: src/lpython/semantics/python_ast_to_asr.cpp [hunk 1]
```diff
@@ -3455,9 +3455,14 @@ class CommonVisitor : public AST::BaseVisitor<Struct> {
             }
             if (sl->m_step != nullptr) {
                 this->visit_expr(*sl->m_step);
+                ASR::asr_t *tmp_step = tmp;
                 if (!ASRUtils::is_integer(*ASRUtils::expr_type(ASRUtils::EXPR(tmp)))) {
                     throw SemanticError("slice indices must be integers or None", tmp->loc);
                 }
+                ASR::expr_t* val = ASRUtils::expr_value(ASRUtils::EXPR(tmp_step));
+                if (val != nullptr && ASR::down_cast<ASR::IntegerConstant_t>(val)->m_n == 0) {
```
Comment (Thirumalai-Shaktivel) [inline src/lpython/semantics/python_ast_to_asr.cpp:3463]: You can also use `is_value_constant`, but this is also fine, I think.
LGTM!

**Review by czgdp1807 — CHANGES_REQUESTED** [review]
Address https://github.com/lcompilers/lpython/pull/1879/files#r1217472487 and then it should be good.

**Review by czgdp1807 — APPROVED** [review]
