### PR TITLE
ASR: Allow variable access from module using dot

### LINKED ISSUE #1242: ASR: [BUG] Error while using dot to access module variable
```py
% cat a.py
import math

def f():
    print(math.pi, math.e)

f()
```

LPython Output:
```
% lpython a.py 
semantic error: Only Variable type is supported for now in Attribute
 --> a.py:4:11
  |
4 |     print(math.pi, math.e)
  |           ^^^^^^^ 
```

CPython:
```
% python a.py 
3.141592653589793 2.718281828459045
```

### PR DESCRIPTION
**Pull request by Smit-create**
Fixes #1242

### CODE REVIEW

File: src/lpython/semantics/python_ast_to_asr.cpp [hunk 1]
```diff
@@ -4391,6 +4391,13 @@ class BodyVisitor : public CommonVisitor<BodyVisitor> {
                 tmp = ASR::make_EnumValue_t(al, x.base.base.loc, enum_member_var,
                         enum_t, enum_member_variable->m_type,
                         ASRUtils::expr_value(enum_member_variable->m_symbolic_value));
+            } else if (ASR::is_a<ASR::Module_t>(*t)) {
+                ASR::Module_t *m = ASR::down_cast<ASR::Module_t>(t);
+                ASR::symbol_t *sym = import_from_module(al, m, current_scope, value,
+                                    x.m_attr, x.m_attr, x.base.base.loc);
+                LFORTRAN_ASSERT(ASR::is_a<ASR::ExternalSymbol_t>(*sym));
+                current_scope->add_symbol(x.m_attr, sym);
```
Comment (czgdp1807) [inline src/lpython/semantics/python_ast_to_asr.cpp:4399]: What if its already imported and added? We will add it to the current scope even though its already there?

Comment (Smit-create) [reply src/lpython/semantics/python_ast_to_asr.cpp:4399]: I think that here we should change the name of the symbol too. If we are already using some variable with the same name then it might be a conflict, for example:
```py
import math

def f():
    pi: f64 = 4.5030
    print(math.pi, math.e)

f()
```
This gives an error:
```
semantic error: pi already defined
```

To tackle this, we need to change the symbol name to `module_name@attr_name`.

> We will add it to the current scope even though its already there?

`import_from_module` ensures that the symbol is not present in the `current_scope`.

Comment (czgdp1807) [reply src/lpython/semantics/python_ast_to_asr.cpp:4399]: > To tackle this, we need to change the symbol name to `module_name@attr_name`.

Correct, name mangling is needed here I think. @certik Thoughts?

> `import_from_module` ensures that the symbol is not present in the `current_scope`.

Please test this. Try using `math.pi` twice.

File: src/lpython/semantics/python_ast_to_asr.cpp [hunk 2]
```diff
@@ -395,13 +395,14 @@ ASR::Module_t* load_module(Allocator &al, SymbolTable *symtab,
...
-                const Location &loc) {
+                const Location &loc, bool skip_current_scope_check=false) {
     ASR::symbol_t *t = m->m_symtab->resolve_symbol(cur_sym_name);
     if (!t) {
         throw SemanticError("The symbol '" + cur_sym_name + "' not found in the module '" + mname + "'",
                 loc);
     }
-    if (current_scope->get_scope().find(cur_sym_name) != current_scope->get_scope().end()) {
+    if (!skip_current_scope_check &&
+        current_scope->get_scope().find(cur_sym_name) != current_scope->get_scope().end()) {
```
Comment (czgdp1807) [inline src/lpython/semantics/python_ast_to_asr.cpp:405]: I think the check should be on `new_sym_name` as that's the mangled thing, correct?

Comment (Smit-create) [reply src/lpython/semantics/python_ast_to_asr.cpp:405]: Yes, I think that's a typo and needs to be fixed. Thanks!

File: src/lpython/semantics/python_ast_to_asr.cpp (hunk 1 above)
Comment (Smit-create) [reply src/lpython/semantics/python_ast_to_asr.cpp]: Done!

**Review by czgdp1807 — APPROVED** [review]
