### PR TITLE
Fixed scoping issues of for loops in global scope

### LINKED ISSUE #1475: For loop should be implemented for strings without declaration
Related to #206 which was closed couple of days ago.

```
a :str
for a in "abc":
      print (a)

(lp) C:\Users\kunni\lpython>python try.py
a
b
c

(lp) C:\Users\kunni\lpython>src\bin\lpython try.py
semantic error: Only function call `range(..)` supported as for loop iteration for now
 --> try.py:3:5 - 4:17
  |
3 |        for a in "abc":
  |        ^^^^^^^^^^^^^^^...
...
  |
4 |            print (a)
  | ...^^^^^^^^^^^^^^^^^
```
Considering `range` is the only supported function, a string input is not another function like `reverse(str_name)` or `enumerate(str_name)` so a better error message can be provided if this is not in the implementation plan as of now.

### LINKED ISSUE #2608: Bug: Segmentation Fault while looping through a `for...in` loop on a `ConstantList` or `StringConstant` or subscripts of the same
### Example 1
```python
from lpython import i32, list
i: i32
for i in [1, 2, 3, 4, 5]:
    print(i)
```
### Example 2
```python
from lpython import i32, list

i: i32
l: list[i32] = [1, 2, 3, 4]
for i in l[1:3]:
    print(i)
```
The same is true for a `StringConstant`.
### Stacktrace
```console
(base) saurabh-kumar@Awadh:~/Projects/System/lpython$ ./src/bin/lpython ./examples/example.py
Traceback (most recent call last):
  Binary file "/home/saurabh-kumar/Projects/System/lpython/src/bin/lpython", in _start()
  File "./csu/../csu/libc-start.c", line 360, in __libc_start_main_impl()
  File "./csu/../sysdeps/x86/libc-start.c", line 58, in __libc_start_call_main()
  File "/home/saurabh-kumar/Projects/System/lpython/src/bin/lpython.cpp", line 1932, in main()
    err = compile_python_to_object_file(arg_file, tmp_o, runtime_library_dir,
  File "/home/saurabh-kumar/Projects/System/lpython/src/bin/lpython.cpp", line 838, in compile_python_to_object_file()
    !(arg_c && compiler_options.po.disable_main), "__main__", infile);
  File "/home/saurabh-kumar/Projects/System/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 8150, in LCompilers::LPython::python_ast_to_asr(Allocator&, LCompilers::LocationManager&, LCompilers::SymbolTable*, LCompilers::LPython::AST::ast_t&, LCompilers::diag::Diagnostics&, LCompilers::CompilerOptions&, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool)
    ast_overload, allow_implicit_casting);
  File "/home/saurabh-kumar/Projects/System/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 8087, in LCompilers::LPython::body_visitor(Allocator&, LCompilers::LocationManager&, LCompilers::LPython::AST::Module_t const&, LCompilers::diag::Diagnostics&, LCompilers::ASR::asr_t*, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::map<int, LCompilers::ASR::symbol_t*, std::less<int>, std::allocator<std::pair<int const, LCompilers::ASR::symbol_t*> > >&, bool)
    b.visit_Module(ast);
  File "/home/saurabh-kumar/Projects/System/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 4732, in LCompilers::LPython::BodyVisitor::visit_Module(LCompilers::LPython::AST::Module_t const&)
    visit_stmt(*x.m_body[i]);
  File "/home/saurabh-kumar/Projects/System/lpython/src/lpython/python_ast.h", line 1883, in LCompilers::LPython::AST::BaseVisitor<LCompilers::LPython::BodyVisitor>::visit_stmt(LCompilers::LPython::AST::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/saurabh-kumar/Projects/System/lpython/src/lpython/python_ast.h", line 1759, in visit_stmt_t<LCompilers::LPython::BodyVisitor>()
    case stmtType::For: { v.visit_For((const For_t &)x); return; }
  File "/home/saurabh-kumar/Projects/System/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 5477, in LCompilers::LPython::BodyVisitor::visit_For(LCompilers::LPython::AST::For_t const&)
    current_body->push_back(al, ASRUtils::STMT(assign));
  File "/home/saurabh-kumar/Projects/System/lpython/src/libasr/containers.h", line 110, in LCompilers::Vec<LCompilers::ASR::stmt_t*>::push_back(Allocator&, LCompilers::ASR::stmt_t*)
    LCOMPILERS_ASSERT(reserve_called == vec_called_const);
  Binary file "/lib/x86_64-linux-gnu/libc.so.6", in __GI___sigaction()
Segfault: Signal SIGSEGV (segmentation fault) received
```

### PR DESCRIPTION
**Pull request by tanay-man**
fixes #2608  , fixes #1475.

### CODE REVIEW

**Comment by kmr-srbh** [comment]
@tanay-man I think this should also fix #1475. Could you please verify it?

File: src/lpython/semantics/python_ast_to_asr.cpp [hunk 1]
```diff
@@ -5565,7 +5565,12 @@ class BodyVisitor : public CommonVisitor<BodyVisitor> {
             ASR::asr_t* assign = ASR::make_Assignment_t(al, x.base.base.loc,
                             ASRUtils::EXPR(ASR::make_Var_t(al, x.base.base.loc, tmp_assign_variable_sym)),
                             target, nullptr);
-            current_body->push_back(al, ASRUtils::STMT(assign));
+            if(current_body){
+                current_body->push_back(al, ASRUtils::STMT(assign));
+            }else{
+                global_init.reserve(al, x.n_body + 1);
+                global_init.push_back(al,assign);
+            }
```
Comment (kmr-srbh) [inline src/lpython/semantics/python_ast_to_asr.cpp:5573]:
```suggestion
            if (current_body) {
                current_body->push_back(al, ASRUtils::STMT(assign));
            } else {
                global_init.reserve(al, 1);
                global_init.push_back(al, assign);
            }
```

We need to reserve only 1 unit for the new assignment. `x.n_body` is the total number of statements present inside the `for` loop body.

Comment (tanay-man) [reply src/lpython/semantics/python_ast_to_asr.cpp:5573]: Actually the reserve call isn't even needed.

**Comment by kmr-srbh** [comment]
Please make the changes to handle subscripts also.

**Comment by tanay-man** [comment]
> @tanay-man I think this should also fix #1475. Could you please verify it?
It does fix the issue.

**Comment by kmr-srbh** [comment]
> It does fix the issue.

Great! Please link the PR to close that too.

**Comment by tanay-man** [comment]
> Please make the changes to handle subscripts also.

The same solution doesn't work for the subscripts. It produces asr but it cannot be converted to llvm further. I'll have to look into it for further analysis.

**Comment by kmr-srbh** [comment]
> > Please make the changes to handle subscripts also.
> 
> The same solution doesn't work for the subscripts. It produces asr but it cannot be converted to llvm further. I'll have to look into it for further analysis.

I tested the changes locally. String subscripts work. We need to handle subscripts for lists.

```python
c: str
my_string: str = "abcd"
for c in my_string[1:3]:
    print(c)
```
```console
(base) saurabh-kumar@Awadh:~/Projects/System/lpython$ ./src/bin/lpython ./examples/example.py
b
c
```

**Comment by kmr-srbh** [comment]
> > Please make the changes to handle subscripts also.
> 
> The same solution doesn't work for the subscripts. It produces asr but it cannot be converted to llvm further. I'll have to look into it for further analysis.

I tested the changes locally. They work for both subscripts of strings and lists.

### List
```python
from lpython import i32

i: i32
my_list: list[i32] = [1, 2, 3, 4, 5]
for i in my_list[1:3]:
    print(i)
```
```console
(base) saurabh-kumar@Awadh:~/Projects/System/lpython$ ./src/bin/lpython ./examples/example.py
2
3
```

### String
```python
c: str
s: str = "abcde"
for c in s[1:3]:
    print(c)
```
```console
(base) saurabh-kumar@Awadh:~/Projects/System/lpython$ ./src/bin/lpython ./examples/example.py
b
c
```

**Comment by kmr-srbh** [comment]
> Issue #2608 , Issue #1475.

@tanay-man you can write fixes #2608, fixes #1475 to link this PR to the issues. :+1:

File: src/lpython/semantics/python_ast_to_asr.cpp (hunk 1 above)
Comment (kmr-srbh) [reply src/lpython/semantics/python_ast_to_asr.cpp]: @tanay-man Please add the whitespaces at the appropriate places.

File: integration_tests/CMakeLists.txt [hunk 2]
```diff
@@ -514,7 +514,7 @@ RUN(NAME loop_03             LABELS cpython llvm llvm_jit c wasm wasm_x64)
 RUN(NAME loop_04             LABELS cpython llvm llvm_jit c)
 RUN(NAME loop_05             LABELS cpython llvm llvm_jit c)
 RUN(NAME loop_06             LABELS cpython llvm llvm_jit c NOFAST)
-RUN(NAME loop_07             LABELS cpython llvm llvm_jit c)
+RUN(NAME loop_07             LABELS cpython llvm llvm_jit)
```
Comment (certik) [inline integration_tests/CMakeLists.txt:517]: Since this doesn't work with the C backend anymore, can you please create a separate test for the new tests that you added?

File: src/lpython/semantics/python_ast_to_asr.cpp [hunk 3]
```diff
@@ -5533,7 +5531,11 @@ class BodyVisitor : public CommonVisitor<BodyVisitor> {
                 ASR::asr_t* assign = ASR::make_Assignment_t(al, x.base.base.loc,
                                 ASRUtils::EXPR(ASR::make_Var_t(al, x.base.base.loc, tmp_assign_variable_sym)),
                                 target, nullptr);
-                current_body->push_back(al, ASRUtils::STMT(assign));
+                if (current_body) {
```
Comment (Shaikh-Ubaid) [inline src/lpython/semantics/python_ast_to_asr.cpp:5534]: Let's be explicit here

```suggestion
                if (current_body != nullptr) {
```

This way we get to know that `current_body` is a pointer (and not an integer or any other type).

File: src/lpython/semantics/python_ast_to_asr.cpp [hunk 4]
```diff
@@ -5565,7 +5567,11 @@ class BodyVisitor : public CommonVisitor<BodyVisitor> {
             ASR::asr_t* assign = ASR::make_Assignment_t(al, x.base.base.loc,
                             ASRUtils::EXPR(ASR::make_Var_t(al, x.base.base.loc, tmp_assign_variable_sym)),
                             target, nullptr);
-            current_body->push_back(al, ASRUtils::STMT(assign));
+            if (current_body) {
```
Comment (Shaikh-Ubaid) [inline src/lpython/semantics/python_ast_to_asr.cpp:5570]:
```suggestion
            if (current_body != nullptr) {
```

File: integration_tests/CMakeLists.txt (hunk 2 above)
Comment (Shaikh-Ubaid) [reply integration_tests/CMakeLists.txt:517]: Yes, @tanay-man  please create a separate test for the new test.

**Review by Shaikh-Ubaid — COMMENTED** [review]
I shared few comments. Apart from the removed `c` label for one of the tests, the rest of the things look good to me. 

I think this will be good to merge after the shared comments are resolved. Thanks for this. Great work @tanay-man !

File: integration_tests/loop_11.py [hunk 5]
```diff
@@ -0,0 +1,37 @@
...
+    print(i)
+    sum += i
+assert sum == 5
+
+sum = 0
+nested_list : list[list[i32]] = [[1, 2, 3, 4]]
+for i in nested_list[0]:
+    print(i)
+    sum += i
+assert sum == 10
```
Comment (Shaikh-Ubaid) [inline integration_tests/loop_11.py:37]: Do you mind printing each value before the assert? That way it is helpful when debugging.

Comment (Shaikh-Ubaid) [reply integration_tests/loop_11.py:37]: Yes.

Comment (tanay-man) [reply integration_tests/loop_11.py:41]: Done.

File: integration_tests/loop_11.py [hunk 6]
```diff
@@ -0,0 +1,41 @@
+from lpython import i32
+
+#checking for loops in the global scope 
+sum: i32 = 0
+i: i32
+for i in [1, 2, 3, 4]:
+    print(i)
+    sum += i
+print("sum = "+str(sum))
```
Comment (kmr-srbh) [inline integration_tests/loop_11.py:9]:
```suggestion
print("sum = ", sum)
```

This is a minor thing. Explicit casting to `str` is not required. Also, let's use a comma instead of the `+` operator. It is typically not used in Python inside `print()`.

Comment (tanay-man) [reply integration_tests/loop_11.py]: Ok

**Review by Shaikh-Ubaid — APPROVED** [review]
It looks good to me. Thanks for this! Great work @tanay-man!
