### PR TITLE
Handle printing of logical types in the LLVM backend

### LINKED ISSUE #322: Handle printing of logical types
Reference code:
```python
b: bool
b = True
print(b)
```
```
% lpython t.py && ./a.out
code generation error: Printing support is available only
                                            for 32, and 64 bit integer kinds.
 --> o.py:3:1
  |
3 | print(b)
  | ^^^^^^^^


Note: if any of the above error or warning messages are not clear or are lacking
context please report it to us (we consider that a bug that needs to be fixed).
```

### PR DESCRIPTION
**Pull request by namannimmo10**
fixes #322

### CODE REVIEW

File: src/libasr/codegen/asr_to_llvm.cpp [hunk 1]
```diff
@@ -3833,6 +3832,17 @@ class ASRToLLVMVisitor : public ASR::BaseVisitor<ASRToLLVMVisitor>
...
+            } else if (ASRUtils::is_logical(*t)) {
+                int ivalue = down_cast<ASR::LogicalConstant_t>(
+                                       ASRUtils::expr_value(v))->m_value;
+                std::string logical_str;
+                if (ivalue == 1) {
+                    logical_str = "True";
+                } else {
+                    logical_str = "False";
+                }
+                llvm::Value *fmt_ptr = builder->CreateGlobalStringPtr(logical_str);
```
Comment (czgdp1807) [inline src/libasr/codegen/asr_to_llvm.cpp:3844]: I think this will work only if `v` is a constant? What if `v` is a variable? I think we should generate the `if-else` check in LLVM (should be easy to do) to select a LLVM string to be stored in `fmt_ptr`.

**Comment by czgdp1807** [comment]
I reviewed. Thanks for requesting review.

File: src/libasr/codegen/asr_to_llvm.cpp (hunk 1 above)
Comment (certik) [reply src/libasr/codegen/asr_to_llvm.cpp:3844]: Yes, this will only work at compile time. One has to pass in the strings `True`/`False` for Python and `.true.`/`.false.` for Fortran at compile time, and then at runtime select true or false, using either a C function or some logic in LLVM.

Comment (czgdp1807) [reply src/libasr/codegen/asr_to_llvm.cpp:3844]: @namannimmo10 Are you still working on this?

Comment (namannimmo10) [reply src/libasr/codegen/asr_to_llvm.cpp:3844]: Thanks for the ping and for reviewing the PR.  Please feel free to move with this; I'm focusing more on refactoring the ASR as of now. If you don't have time, I can come back to it this week.

**Comment by Smit-create** [comment]
I think this is already fixed in `main`. 
```
print(True, False)
```

Gives,
```
1 0
```

Handling booleans as integers in the LLVM backend is good in my opinion because ASR is language independent and the LLVM backend is used for different frontend languages, we might have some confits in printing booleans explicitly like "True" in some front-end languages and "true" in some others.

**Comment by certik** [comment]
The issue is that LPython should print it like CPython does, and LFortran like other Fortran compilers do. But this can be easily configurable, say as an option to `asr_to_llvm`, so not a big deal in practice.

**Comment by namannimmo10** [comment]
I am sorry for the long delay in addressing the comments. This can go in now.

**Review by certik — APPROVED** [review]
I think this works. Thanks!
