### PR TITLE
Fix warning

### LINKED ISSUE #1018: Fix warnings in main
On M1
```
In file included from /Users/ondrej/repos/lpython/src/lpython/semantics/python_ast_to_asr.cpp:27:
/Users/ondrej/repos/lpython/src/lpython/semantics/python_comptime_eval.h:698:23: warning: unused variable 'arg_type' [-Wunused-variable]
        ASR::ttype_t *arg_type = ASRUtils::expr_type(arg);
                      ^
/Users/ondrej/repos/lpython/src/lpython/semantics/python_comptime_eval.h:715:23: warning: unused variable 'arg_type' [-Wunused-variable]
        ASR::ttype_t *arg_type = ASRUtils::expr_type(arg);
                      ^
/Users/ondrej/repos/lpython/src/lpython/semantics/python_comptime_eval.h:718:20: warning: comparison of integers of different signs: 'int' and 'std::basic_string<char>::size_type' (aka 'unsigned long') [-Wsign-compare]
        while (ind < res.size() && res[ind++] == ' ');
               ~~~ ^ ~~~~~~~~~~
/Users/ondrej/repos/lpython/src/lpython/semantics/python_comptime_eval.h:732:23: warning: unused variable 'arg_type' [-Wunused-variable]
        ASR::ttype_t *arg_type = ASRUtils::expr_type(arg);
                      ^
/Users/ondrej/repos/lpython/src/lpython/semantics/python_comptime_eval.h:735:18: warning: comparison of integers of different signs: 'int' and 'std::basic_string<char>::size_type' (aka 'unsigned long') [-Wsign-compare]
        while (l < res.size() && r >= 0 && (res[l] == ' ' || res[r] == ' ')) {
               ~ ^ ~~~~~~~~~~
/Users/ondrej/repos/lpython/src/lpython/semantics/python_ast_to_asr.cpp:4551:32: warning: comparison of integers of different signs: 'int' and 'std::basic_string<char>::size_type' (aka 'unsigned long') [-Wsign-compare]
                    while (ind < res.size() && res[ind] == ' ') {
                           ~~~ ^ ~~~~~~~~~~
/Users/ondrej/repos/lpython/src/lpython/semantics/python_ast_to_asr.cpp:4567:30: warning: comparison of integers of different signs: 'int' and 'std::basic_string<char>::size_type' (aka 'unsigned long') [-Wsign-compare]
                    while (l < res.size() && r >= 0 && (res[l] == ' ' || res[r] == ' ')) {
                           ~ ^ ~~~~~~~~~~
7 warnings generated.

```

### PR DESCRIPTION
**Pull request by Abdelrahman-Kh-Fouad**
Fix #1018 issue.

### CODE REVIEW

**Comment by czgdp1807** [comment]
Thanks. This will enable easy debugging.

**Review by czgdp1807 — APPROVED** [review]

File: src/lpython/semantics/python_ast_to_asr.cpp [hunk 1]
```diff
@@ -4602,7 +4602,7 @@ class BodyVisitor : public CommonVisitor<BodyVisitor> {
                     AST::ConstantStr_t *n = AST::down_cast<AST::ConstantStr_t>(at->m_value);
                     std::string res = n->m_value;
                     int ind = 0;
-                    while (ind < res.size() && res[ind] == ' ') {
+                    while (ind < (int)res.size() && res[ind] == ' ') {
```
Comment (czgdp1807) [inline src/lpython/semantics/python_ast_to_asr.cpp:4605]: Instead of casting `res.size()` to `int` can you try the following,

`size_t ind = 0;`

This review applies elsewhere in your PR as well.

Comment (Abdelrahman-Kh-Fouad) [reply src/lpython/semantics/python_ast_to_asr.cpp:4605]: it makes variables unsigned, so it raise warinng like this 
```bash
warning: comparison of unsigned expression in ‘>= 0’ is always true [-Wtype-limits]
  700 |         while (ind >= 0 && res[ind--] == ' ');
      |                ~~~~^~~~
```
to fix this i will casting `ind` when i compare it with zero `ind >=0 `, so it's the same as casting the `size` it self i think.
am i right?

Comment (czgdp1807) [reply src/lpython/semantics/python_ast_to_asr.cpp:4605]: Makes sense. @certik Should we merge this then?

**Review by certik — APPROVED** [review]
I think this is fine.
