### PR TITLE
Fixed Printing of Escape Sequences

### LINKED ISSUE #1473: Escape sequence recognized but not ignored in printing.
The parser identifies backslash as an escape sequence and allows the printing but the `\` also gets printed.

```
    s: str
    s = 'I said 'Wow' '  # Without escape sequence 
    print(s)

(lp) C:\Users\kunni\lpython>python try.py
  File "C:\Users\kunni\lpython\try.py", line 3
    s = 'I said 'Wow''
                 ^^^
SyntaxError: invalid syntax

(lp) C:\Users\kunni\lpython>src\bin\lpython try.py
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
LCompilersException: The string is not recognized by the parser.
```
```
    s: str
    s = 'I said \'Wow\' '  # With escape sequence
    print(s)

(lp) C:\Users\kunni\lpython>python try.py
I said 'Wow'

(lp) C:\Users\kunni\lpython>src\bin\lpython try.py
   Creating library try.lib and object try.exp
I said \'Wow\'
```

### PR DESCRIPTION
**Pull request by gptsarthak**
Fixes #1473
Modified LPython semantics, C and Julia backend so that they do not print the backslash even after it is recognized.

When asked to print the following string: 
```
s: str
s = 'I said \'Wow\' '
print(s)
``` 
LPython now prints:
`I said 'Wow' `

### CODE REVIEW

File: src/lpython/parser/semantics.h [hunk 1]
```diff
@@ -800,7 +800,10 @@ char* unescape(Allocator &al, LCompilers::Str &s) {
         if (s.p[idx] == '\\' && s.p[idx+1] == 'n') {
             x += "\n";
             idx++;
-        } else {
+        }else if (s.p[idx] == '\\' && s.p[idx+1] == '\'') {
```
Comment (certik) [inline src/lpython/parser/semantics.h:803]:
```suggestion
        } else if (s.p[idx] == '\\' && s.p[idx+1] == '\'') {
```

File: src/lpython/parser/semantics.h [hunk 2]
```diff
@@ -800,7 +800,10 @@ char* unescape(Allocator &al, LCompilers::Str &s) {
...
+            x += "'";
+            idx++;
+        }else {
```
Comment (certik) [inline src/lpython/parser/semantics.h:806]:
```suggestion
        } else {
```

File: tests/reference/ast_new-string2-44323ea.stdout [hunk 3]
```diff
@@ -8,5 +8,5 @@ class a:
 " ())] [])) (Expr (ConstantStr "
     "\\"
 " ())) (Expr (ConstantStr "
-    '\\'
+    '\'
```
Comment (certik) [inline tests/reference/ast_new-string2-44323ea.stdout:11]: I checked against CPython and this change seems to be correct.

**Review by certik — APPROVED** [review]
I think this looks good, thanks for fixing it! I left some minor formatting comments.

**Comment by certik** [comment]
Thanks @gptsarthak for the fix!

**Comment by faze-geek** [comment]
The obvious edge case to be checked here was for `" "` instead of `' '` :)
Just as I was writing this comment the PR was merged.
```
def main():
	print("I said \"hi\" ")

main()

(lp) C:\Users\kunni\lpython>python try.py
I said "hi"

(lp) C:\Users\kunni\lpython>src\bin\lpython try.py
I said \"hi\"
```
@gptsarthak Shouldn't be difficult to add this. Thanks !

**Comment by gptsarthak** [comment]
Hey @faze-geek thanks for pointing it out! Now that this PR is merged, should I make another PR after adding it?

**Comment by faze-geek** [comment]
> Hey @faze-geek thanks for pointing it out! Now that this PR is merged, should I make another PR after adding it?

Yes, you can do that!
I noticed you made the changes from your main. It's better to always make a new branch instead.
