### PR TITLE
Fixes floor div errors

### LINKED ISSUE #318: Floor division giving incorrect results
Runtime:
```console
$ cat a.py 
def f():
    x: i32
    x = 5
    print(x//2)
    print(-x//2)

f()
$ lpython a.py && ./a.out 
2
2147483645
$ python a.py 
2
-3
```
Compile time:
```console
$ cat a.py 
def f():
    print(5//2)
    print(-5//2)

f()
$ lpython a.py && ./a.out
2
-2
$ python a.py            
2
-3
```

Both are wrong for the negative numbers compared to the reference CPython result.

### PR DESCRIPTION
**Pull request by Smit-create**
Fixes #318

### CODE REVIEW

File: src/lpython/semantics/python_comptime_eval.h [hunk 1]
```diff
@@ -534,19 +534,44 @@ struct PythonIntrinsicProcedures {
...
-            ASR::expr_t *tmp = ASR::down_cast<ASR::expr_t>(make_ConstantReal_t(al, loc, n/d, type));
-            tmp = ASR::down_cast<ASR::expr_t>(ASR::make_ImplicitCast_t(
-                al, tmp->base.loc, tmp, ASR::cast_kindType::RealToInteger,
-                int_type, nullptr));
-            return ASR::down_cast<ASR::expr_t>(ASR::make_ImplicitCast_t(
-                al, tmp->base.loc, tmp, ASR::cast_kindType::IntegerToReal,
-                type, nullptr));
+            double d = ASR::down_cast<ASR::ConstantReal_t>(arg2)->m_r;
+            double r = n/d, res = 0.0;
+            int64_t ival = (int64_t)r;
```
[the remark this answers is not in the document]
Comment (Smit-create) [reply src/lpython/semantics/python_comptime_eval.h:547]: I think it's good to write the cast so that's it's visible clearly.

[the remark this answers is not in the document]
Comment (certik) [reply src/lpython/semantics/python_comptime_eval.h:547]: It might also fix warnings on some compilers. I agree, I think it is more clear what the intent is to put the cast in explicitly.

File: src/lpython/semantics/python_ast_to_asr.cpp [hunk 2]
```diff
@@ -727,19 +727,22 @@ class CommonVisitor : public AST::BaseVisitor<Derived> {
...
+                Vec<ASR::call_arg_t> args;
+                args.reserve(al, 1);
+                ASR::call_arg_t arg1, arg2;
+                arg1.loc = left->base.loc;
+                arg2.loc = right->base.loc;
+                arg1.m_value = left;
+                arg2.m_value = right;
+                args.push_back(al, arg1);
+                args.push_back(al, arg2);
+                tmp = make_call_helper(al, fn_div, current_scope, args, "_lpython_floordiv", loc);
```
Comment (certik) [inline src/lpython/semantics/python_ast_to_asr.cpp:744]: Does this work even when (now) the `_lpython_floordiv` is a GenericFunction?

**Review by certik — APPROVED** [review]
This looks good. Needs a rebase / update tests.

**Comment by certik** [comment]
@namannimmo10 thanks for fixing the test to run.

File: src/lpython/semantics/python_ast_to_asr.cpp (hunk 2 above)
Comment (Smit-create) [reply src/lpython/semantics/python_ast_to_asr.cpp:744]: Yeah, this works fine.

**Comment by Smit-create** [comment]
Tests pass locally for me. Is there any issue with tokens tests?

File: tests/reference/tokens-docstring1-1355fbb.stdout [hunk 3]
```diff
@@ -4,38 +4,32 @@
 (TOKEN ")") 10:10
 (TOKEN ":") 11:11
 (NEWLINE) 12:12
-(TOKEN "indent") 13:16
```
Comment (Thirumalai-Shaktivel) [inline tests/reference/tokens-docstring1-1355fbb.stdout:7]: The removal of this line and other subsequent lines caused the CI to fail.

Comment (Smit-create) [reply tests/reference/tokens-docstring1-1355fbb.stdout:7]: Actually, I didn't change them manually. I just ran `./run_tests.py -u`.

Comment (Thirumalai-Shaktivel) [reply tests/reference/tokens-docstring1-1355fbb.stdout:7]: Yup, No issues. I think now the CI should pass

**Comment by Smit-create** [comment]
CI is green, thanks for the fixes @Thirumalai-Shaktivel
